server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/soundbook_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=041299

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

google.client-id=264640047149-qrrlqpraqqsoj9tijuk55tndve952opu.apps.googleusercontent.com

# Spotify OAuth
spotify.client-id=b07b0e491f2148dc8cc798971f25faff
spotify.client-secret=42d77cb1dd86496789b6dcb62be3a598
spotify.redirect-uri=http://127.0.0.1:8081/api/v1/integrations/spotify/callback
spotify.frontend-base-url=http://localhost:5173
spotify.scope=user-read-private user-top-read user-read-recently-played
spotify.state-expiration-ms=600000

# YouTube API
youtube.api-key=AIzaSyA-z9mOZDEs5h0QGqsHpyNvsIGZs__NzyI
google.api-key=AIzaSyBns0hSOFq6L_E8LtTBRzpUVJG0KvptfFk

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

gemini.api-key=${GEMINI_API_KEY}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

