server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/soundbook_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=thien2005@

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Mật khẩu bí mật sinh mã JWT (Base64 Encode của 1 chuỗi dài ngẫu nhiên >= 256bit)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Hạn sử dụng: 24h = 86400000 ms
app.jwt.expiration-ms=86400000

google.client-id=320147041734-hkso7lionh433otua25vm34nbangsbns.apps.googleusercontent.com

# Spotify OAuth
spotify.client-id=b07b0e491f2148dc8cc798971f25faff
spotify.client-secret=42d77cb1dd86496789b6dcb62be3a598
spotify.redirect-uri=http://127.0.0.1:8081/api/v1/integrations/spotify/callback
spotify.frontend-base-url=http://localhost:5173
spotify.scope=user-read-private user-top-read user-read-recently-played
spotify.state-expiration-ms=600000