server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/soundbook_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=thien2005@

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# M?t kh?u bí m?t sinh mã JWT (Base64 Encode c?a 1 chu?i dài ng?u nhiên >= 256bit)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# H?n s? d?ng: 24h = 86400000 ms
app.jwt.expiration-ms=86400000
google.client-id=320147041734-hkso7lionh433otua25vm34nbangsbns.apps.googleusercontent.com